# Generated by Django 5.1.1 on 2024-09-24 11:58

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/avatar/sen.png', upload_to=profiles.models.upload_to),
        ),
    ]
